"""User Roles

Revision ID: bd4d5c565646
Revises: 892dc278dfbd
Create Date: 2020-12-15 20:39:25.153180

"""

# revision identifiers, used by Alembic.
revision = 'bd4d5c565646'
down_revision = '892dc278dfbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
